### 1.import

In [1]:
import torch

### 2.기초 지식
`-` 선형대수학

-   벡터와 행렬
-   행렬의 곱셉
-   트랜스포즈

`-` 기초통계학(수리통계)

-   정규분포, 이항분포
-   모수, 추정
-   $X_i \overset{i.i.d.}{\sim} N(0,1)$

`-` 회귀분석

-   독립변수($y$), 설명변수($X$)
-   ${\boldsymbol y} = {\bf X}{\boldsymbol \beta} + {\boldsymbol \epsilon}$

`-` 파이썬

-   파이썬 기본문법
-   넘파이, 판다스
-   전반적인 클래스 지식 (`__init__`, `self`, …)
-   상속

### 3. torch

#### A.벡터

In [2]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

* 벡터끼리 덧셈

In [3]:
torch.tensor([1,2,3]) + torch.tensor([3,3,3])

tensor([4, 5, 6])

* 브로드캐스팅 가능 -> 위에와 똑같은 기능

In [7]:
torch.tensor([1,2,3])+2

tensor([3, 4, 5])

In [5]:
torch.tensor([1,2,3])+torch.tensor([2])

tensor([3, 4, 5])

In [6]:
torch.tensor([1,2,3])+torch.tensor(2)

tensor([3, 4, 5])

#### B. 벡터와 매트릭스

* 3x2 matrix

In [8]:
torch.tensor([[1,2],[3,4],[5,6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

* 3X1 matrix 는 3X1 열벡터(column vector)와 같음

In [10]:
torch.tensor([[1],[2],[3]]) 

tensor([[1],
        [2],
        [3]])

* 1X2 matrix 는 1X2 행벡터(row vector)와 같음

In [12]:
torch.tensor([[1,2]]) 

tensor([[1, 2]])

#### c. matrix 덧셈

* 브로드캐스팅(숫자하나)

In [13]:
torch.tensor([[1,2],[3,4],[5,6]]) - 1

tensor([[0, 1],
        [2, 3],
        [4, 5]])

* 아래와 같은 의미임

In [15]:
torch.tensor([[1,2],[3,4],[5,6]]) - torch.tensor([[1,1],[1,1],[1,1]])

tensor([[0, 1],
        [2, 3],
        [4, 5]])

* 브로드캐스팅(열)

In [16]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1],[-3],[-5]])

tensor([[0, 1],
        [0, 1],
        [0, 1]])

* 아래와 같은 의미임

In [17]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1,-1],[-3,-3],[-5,-5]])

tensor([[0, 1],
        [0, 1],
        [0, 1]])

* 브로드캐스팅(행)

In [18]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1,-2]])

tensor([[0, 0],
        [2, 2],
        [4, 4]])

* 아래와 같은 의미임

In [19]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1,-2],[-1,-2],[-1,-2]])

tensor([[0, 0],
        [2, 2],
        [4, 4]])

***잘못된 브로드캐스팅***

* 열로 브로드캐스팅 하려면 3X1 행렬이어야하지만 여기는 1X3 행렬

In [20]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1,-3,-5]])

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

* 행으로 브로드캐스팅 하려면 1X2 행렬이어야하지만 여기는 2X1 행렬

In [21]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1],[-2]])

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

***그냥 벡터를 넣으면 이상하게 행으로만 브로드캐스팅 됨***

In [22]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([-1,-2])

tensor([[0, 0],
        [2, 2],
        [4, 4]])

* 열로는 안됨..

In [23]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([-1,-3,-5])

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

#### D. 행렬곱